// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmoxanhhjadmeffeotcp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtb3hhbmhoamFkbWVmZmVvdGNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3OTM0MjcsImV4cCI6MjA2NDM2OTQyN30.nuU1RsFzJKmZAH5DPwdYuFlAvUfCG026N95DKn_TYbo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);